version: '3.4'

services:
  supero.tasklist.api:
    image: ${DOCKER_REGISTRY-}superotasklistapi
    build:
      context: .
      dockerfile: Supero.TaskList.Api/Dockerfile
  sql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"